micronaut:
  application:
    name: bolaoMatchesUpdateCronjob
  http:
    client:
      logger-name: client
      read-timeout: ${CLIENT_TIMEOUT:5s}
  server:
    port: ${SERVER_PORT:8082}


netty:
  default:
    allocator:
      max-order: 3

clients:
  backend:
    api-url: ${BACKEND_API_URL}
    base-url: ${BACKEND_BASE_URL}
  football-data-org:
    api-url: ${FOOTBALL_DATA_URL:`https://api.football-data.org`}
    api-key: ${FOOTBALL_DATA_API_KEY}

user-credentials:
  login: ${USER_LOGIN}
  password: ${USER_PASSWORD}

feature:
  update-match-score:
    toggle: true
    cron-expression: ${CRON_EXPRESSION:`0 */5 * * * *`}

