micronaut:
  application:
    name: bolaoMatchesUpdateCronjob
  http:
    client:
      logger-name: client
      read-timeout: ${BMUC_CLIENT_TIMEOUT:5s}
  server:
    port: ${BMUC_SERVER_PORT:8082}


netty:
  default:
    allocator:
      max-order: 3

clients:
  backend:
    api-url: ${BMUC_BACKEND_API_URL}
    base-url: ${BMUC_BACKEND_API_URL}
  football-data-org:
    api-url: ${BMUC_FOOTBALL_DATA_URL:`https://api.football-data.org`}
    api-key: ${BMUC_FOOTBALL_DATA_API_KEY}

user-credentials:
  login: ${BMUC_USER_LOGIN}
  password: ${BMUC_USER_PASSWORD}

feature:
  update-match-score:
    toggle: true
    cron-expression: ${BMUC_CRON_EXPRESSION:`0 */5 * * * *`}

